######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 15 23:03:32 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += xml

# Input
HEADERS += nlptest.h
SOURCES += nlptest.cpp


SOURCES += \
    ../src/recommender/numericalattribute.cpp \
    ../src/recommender/stringattribute.cpp \
    ../src/recommender/relationship.cpp \
    ../src/recommender/critique.cpp \
    ../src/recommender/offer.cpp \
    ../src/recommender/valueattribute.cpp \
    ../src/recommender/critiquerecommender.cpp \
    ../src/spencer.cpp \
    ../src/recommender/attributefactory.cpp \
    ../src/recommender/compoundattribute.cpp

HEADERS += \
    ../src/recommender/attribute.h \
    ../src/recommender/numericalattribute.h \
    ../src/recommender/stringattribute.h \
    ../src/recommender/relationship.h \
    ../src/recommender/critique.h \
    ../src/recommender/offer.h \
    ../src/recommender/valueattribute.h \
    ../src/recommender/critiquerecommender.h \
    ../src/spencer.h \
    ../src/recommender/attributefactory.h \
    ../src/recommender/compoundattribute.h

