######################################################################
# Automatically generated by qmake (3.0) Sat Jul 12 16:34:31 2014
######################################################################

QT += testlib xml
TEMPLATE = app
TARGET = test
INCLUDEPATH += . ../src

# Input
HEADERS += nlptest.h \
           ../src/nlu/nlu.h \
           ../src/nlu/statement.h \
           ../src/nlu/usecasestatement.h \
           ../src/nlu/aspectstatement.h \
           ../src/nlu/token.h \
           ../src/nlu/observedtoken.h \
           ../src/nlu/commandstatement.h \
           ../src/nlu/aspectstatement.h \
           ../src/nlu/constraintstatement.h \
           ../src/recommender/critiquerecommender.h \
           ../src/recommender/critique.h \
           ../src/domainbase/offer.h \
           ../src/domainbase/attribute.h \
           ../src/domainbase/attributefactory.h \
           ../src/domainbase/aspectfactory.h \
           ../src/domainbase/relationship.h \
           ../src/domainbase/aspect.h \
           ../src/domainbase/stringattribute.h \
           ../src/domainbase/valueattribute.h \
           ../src/domainbase/numericalattribute.h \
           ../src/domainbase/compoundattribute.h \
           ../src/domainbase/listattribute.h \
           ../src/domainbase/recommendationattribute.h
SOURCES += nlptest.cpp \
           ../src/nlu/nlu.cpp \
           ../src/nlu/statement.cpp \
           ../src/nlu/usecasestatement.cpp \
           ../src/nlu/aspectstatement.cpp \
           ../src/nlu/token.cpp \
           ../src/nlu/observedtoken.cpp \
           ../src/nlu/commandstatement.cpp \
           ../src/nlu/constraintstatement.cpp \
           ../src/recommender/critiquerecommender.cpp \
           ../src/recommender/critique.cpp \
           ../src/domainbase/offer.cpp \
           ../src/domainbase/attribute.cpp \
           ../src/domainbase/attributefactory.cpp \
           ../src/domainbase/aspectfactory.cpp \
           ../src/domainbase/relationship.cpp \
           ../src/domainbase/aspect.cpp \
           ../src/domainbase/stringattribute.cpp \
           ../src/domainbase/valueattribute.cpp \
           ../src/domainbase/compoundattribute.cpp \
           ../src/domainbase/listattribute.cpp \
           ../src/domainbase/numericalattribute.cpp \
           ../src/domainbase/recommendationattribute.cpp
